CREATE TABLE Companies (
    IdCompany INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(150) NOT NULL,
    SwiftCode NVARCHAR(20) NOT NULL,
    Country NVARCHAR(100) NOT NULL,
    IdCountry NVARCHAR(10) NOT NULL,
    Phone NVARCHAR(20) NOT NULL,
    Status INT NOT NULL DEFAULT 1,
    DateC DATETIME NOT NULL DEFAULT GETDATE(),
    UserC NVARCHAR(100) NOT NULL,
    DateU DATETIME NULL,
    UserU NVARCHAR(100) NULL
);